### ISSUE TITLE
Small GUI improvements

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/services-watcher#1]
Just a few suggestions:
- The main window may look less cramped if the spacing to the border was larger.
- Also, you may want to increase the spacing between the list items a bit.
- A selected item should use B_LIST_SELECTED_ITEM_TEXT_COLOR and B_LIST_SELECTED_BACKGROUND_COLOR
- The options may also benefit from a larger spacing to the border. B_USE_WINDOW_SPACING might be the right thing, see InterfaceDefs.h
- To integrate better, use sentence casing in the options window.
- Use "ServicesWatcher" instead "Service Watcher" in the windows' titles.
- You could put  the "Show application name and status in a heading above the radio buttons and use for those simply: "on one line" and "on two lines". Or even simpler, just use one checkbox: "Show application name and status on one line" and have the two-liner as default.
- In the About window, replace haikuware with HaikuDepot, use "ServiceWatcher", update copyright year.

Small stuff... :)

**Comment by Perelandra0x309** [comment]
Implemented most of these suggestions, thanks.
